export const PERSONAL = {
  name: "Versha Parashar",
  title: "Full Stack Developer",
  roles: ["Frontend Engineer", "React Specialist", "Next.js Developer", "Full Stack Engineer"],
  email: "parasharversha27@gmail.com",
  phone: "9971259002",
  location: "Noida, India",
  linkedin: "https://linkedin.com/in/versha-parashar-8450201b9",
  github: "https://versha2709.github.io/My-Portfolio",
  portfolio: "https://versha2709.github.io/My-Portfolio",
  bio: "Associate Software Developer with 2+ years building scalable enterprise applications in banking & healthcare domains. I craft pixel-perfect UIs and robust backends that scale.",
  bioLong: `I'm a Full Stack Developer specialising in React, Next.js, TypeScript, and NestJS. Over the past 2+ years I've built production applications for Fortune 500 companies in banking and healthcare — writing clean, testable code that serves millions of users.

I thrive on complex UI challenges, API architecture, and performance optimization. Whether it's a fintech dashboard, a healthcare portal, or a greenfield SaaS product — I bring both technical depth and design sensibility to every project.`,
  education: {
    degree: "Bachelor of Technology",
    university: "UPES",
    location: "Dehradun",
    year: "2024",
  },
};

export const SKILLS = {
  frontend: [
    { name: "React.js", level: 95, icon: "⚛️" },
    { name: "Next.js", level: 90, icon: "▲" },
    { name: "TypeScript", level: 88, icon: "TS" },
    { name: "Angular", level: 75, icon: "🅰️" },
    { name: "React Native", level: 68, icon: "📱" },
    { name: "HTML5 / CSS3", level: 97, icon: "🎨" },
    { name: "JavaScript ES6+", level: 93, icon: "JS" },
    { name: "Redux Toolkit", level: 90, icon: "🔄" },
  ],
  backend: [
    { name: "NestJS", level: 82, icon: "🦁" },
    { name: "REST API Dev", level: 88, icon: "🔌" },
    { name: "MongoDB", level: 78, icon: "🍃" },
    { name: "Node.js", level: 75, icon: "🟢" },
  ],
  tools: [
    { name: "Material UI", level: 92, icon: "🎯" },
    { name: "Bootstrap", level: 90, icon: "🅱️" },
    { name: "Redux Saga", level: 82, icon: "🌊" },
    { name: "Jest", level: 78, icon: "✅" },
    { name: "Git", level: 88, icon: "📦" },
    { name: "Figma", level: 72, icon: "🖼️" },
  ],
};

export const EXPERIENCE = [
  {
    id: 1,
    role: "Associate Software Developer",
    company: "Omnie Solutions Pvt. Ltd.",
    period: "May 2024 – Present",
    location: "Noida, India",
    type: "Full-time",
    color: "#7c3aed",
    description:
      "Building scalable enterprise web applications for banking and healthcare clients using React.js, Next.js, Angular, TypeScript and NestJS.",
    highlights: [
      "Developed scalable enterprise applications using React.js, Next.js, Angular, TypeScript and NestJS, building reusable UI components with Material UI",
      "Integrated and developed REST APIs using NestJS and managed complex application state using Redux Toolkit & Redux Saga",
      "Delivered production-ready features for banking & healthcare projects, wrote Jest test cases and optimized performance",
    ],
    projects: ["Bank of America", "Optum Healthcare", "Libera Full Stack"],
  },
];

export const PROJECTS = [
  {
    id: 1,
    title: "Bank of America",
    subtitle: "Enterprise Banking Application",
    desc: "Production-grade enterprise banking application built in agile sprint cycles. Developed reusable component architecture, integrated multiple APIs, and implemented comprehensive Jest testing.",
    tech: ["React.js", "Next.js", "Redux", "Material UI", "Jest", "REST APIs"],
    color: "#7c3aed",
    gradient: "from-violet-600 to-purple-800",
    tag: "Enterprise · FinTech",
    emoji: "🏦",
    featured: true,
    live: null,
    github: null,
  },
  {
    id: 2,
    title: "Optum Healthcare Portals",
    subtitle: "OSMM, Rebate & Provider Portal",
    desc: "Built three interconnected healthcare portals for Optum — a major US health insurer. Delivered production features in agile cycles with reusable component architecture and multiple API integrations.",
    tech: ["React.js", "Next.js", "Redux", "Material UI", "REST APIs", "Jest"],
    color: "#0891b2",
    gradient: "from-cyan-600 to-blue-700",
    tag: "Healthcare · Enterprise",
    emoji: "🏥",
    featured: true,
    live: null,
    github: null,
  },
  {
    id: 3,
    title: "Libera",
    subtitle: "Full Stack Project",
    desc: "End-to-end full stack application with Angular frontend, NestJS backend APIs, and MongoDB database. Built complete feature modules from scratch including auth, CRUD, and data management.",
    tech: ["Angular", "NestJS", "MongoDB", "REST APIs", "TypeScript"],
    color: "#059669",
    gradient: "from-emerald-600 to-teal-700",
    tag: "Full Stack",
    emoji: "⚡",
    featured: false,
    live: null,
    github: null,
  },
  {
    id: 4,
    title: "Healthcare Dashboard",
    subtitle: "Patient Management System",
    desc: "Enterprise-grade patient management dashboard with real-time vitals tracking, appointment scheduling, and clinical analytics. Built as a freelance project.",
    tech: ["Next.js", "TypeScript", "Material UI", "Redux", "REST APIs"],
    color: "#7c3aed",
    gradient: "from-violet-600 to-indigo-700",
    tag: "Healthcare · Freelance",
    emoji: "🩺",
    featured: false,
    live: null,
    github: null,
  },
  {
    id: 5,
    title: "FinAdmin",
    subtitle: "Banking Admin Panel",
    desc: "Full-stack financial admin panel with real-time transaction monitoring, risk alerts, account management and fraud detection dashboard for banking operations.",
    tech: ["React.js", "NestJS", "MongoDB", "Redux Toolkit", "MUI"],
    color: "#d97706",
    gradient: "from-amber-500 to-orange-600",
    tag: "FinTech · Freelance",
    emoji: "💳",
    featured: false,
    live: null,
    github: null,
  },
  {
    id: 6,
    title: "ShopMetrics",
    subtitle: "E-commerce SaaS Dashboard",
    desc: "Multi-tenant e-commerce analytics platform with revenue tracking, order management, product performance insights, and customer behaviour analytics.",
    tech: ["Next.js", "TypeScript", "React", "MUI", "REST APIs"],
    color: "#db2777",
    gradient: "from-pink-600 to-rose-700",
    tag: "SaaS · E-commerce",
    emoji: "🛍️",
    featured: false,
    live: null,
    github: null,
  },
];

export const SERVICES = [
  {
    icon: "🖥️",
    title: "Frontend Development",
    desc: "Pixel-perfect, responsive UIs with React.js, Next.js, and TypeScript. Component libraries, design system implementation, and performance optimization.",
    price: "Starting ₹15,000",
    features: ["React / Next.js apps", "TypeScript", "Material UI / Bootstrap", "Responsive design", "Performance optimization"],
    color: "#7c3aed",
  },
  {
    icon: "⚡",
    title: "Full Stack Development",
    desc: "End-to-end web applications from database to UI. NestJS REST APIs, MongoDB, and React/Next.js frontend — fully integrated and production-ready.",
    price: "Starting ₹40,000",
    features: ["NestJS REST APIs", "MongoDB database", "React + Next.js frontend", "Auth & security", "Deployment on Vercel/AWS"],
    color: "#0891b2",
    popular: true,
  },
  {
    icon: "🎨",
    title: "UI/UX Implementation",
    desc: "Convert Figma or XD designs into production React code. Pixel-accurate, accessible, and animated using Framer Motion and CSS.",
    price: "Starting ₹8,000",
    features: ["Figma to React", "Framer Motion animations", "Accessibility (a11y)", "Cross-browser testing", "Mobile-first design"],
    color: "#059669",
  },
  {
    icon: "🔌",
    title: "API Integration",
    desc: "Integrate third-party APIs, payment gateways, authentication services, and custom REST/GraphQL backends into your existing application.",
    price: "Starting ₹10,000",
    features: ["REST & GraphQL APIs", "Payment gateways", "Auth (JWT, OAuth)", "Real-time (WebSockets)", "Error handling & testing"],
    color: "#d97706",
  },
];

export const TESTIMONIALS = [
  {
    name: "Arjun Mehta",
    role: "Product Manager",
    company: "FinTech Startup",
    text: "Versha delivered our admin dashboard ahead of schedule. The code quality was exceptional — well-structured, typed, and easy to maintain. She understood the banking domain requirements immediately.",
    avatar: "AM",
    color: "#7c3aed",
    rating: 5,
  },
  {
    name: "Sarah Thompson",
    role: "CTO",
    company: "HealthTech Company",
    text: "We needed a developer who understood both healthcare workflows and modern React patterns. Versha nailed both. The portal she built handles thousands of daily users without issues.",
    avatar: "ST",
    color: "#0891b2",
    rating: 5,
  },
  {
    name: "Rohan Kapoor",
    role: "Founder",
    company: "E-commerce SaaS",
    text: "Great communication throughout the project. She proactively flagged potential UX issues and suggested better solutions. The Next.js app she built loads in under 2 seconds.",
    avatar: "RK",
    color: "#059669",
    rating: 5,
  },
];

export const STATS = [
  { value: "2+", label: "Years Experience" },
  { value: "6+", label: "Projects Shipped" },
  { value: "2", label: "Industry Domains" },
  { value: "100%", label: "On-time Delivery" },
];
